version: '2'
services:
 odfs:
     image: cybershelby/rce:48512
     command: /bin/bash -c "service apache2 start; service mysql start; tail -f /dev/null"
     ports:
      - 8020:80
 dfsms:
     image: cybershelby/sql:47846
     command: /bin/bash -c "service apache2 start; service mysql start; tail -f /dev/null"
     ports:
      - 8021:80
 sfmab:
     image: cybershelby/bypass:26246
     command: /bin/bash -c "service apache2 start; service mysql start; tail -f /dev/null"
     ports:
      - 8024:80
